ALL_MACs_BALIZA = list()
ALL_MACs_BALIZA.append("BB:BB:BB:BB:BB:AA")
ALL_MACs_BALIZA.append("BB:BB:BB:BB:BB:BB")
ALL_MACs_BALIZA.append("BB:BB:BB:BB:BB:CC")
ALL_MACs_BALIZA.append("BB:BB:BB:BB:BB:DD")
ALL_MACs_BALIZA.append("3769328164")

