ALL_MACs_MANITOR = list()
ALL_MACs_MANITOR.append("AA:AA:AA:AA:AA:AA")
ALL_MACs_MANITOR.append("AA:AA:AA:AA:AA:BB")
ALL_MACs_MANITOR.append("AA:AA:AA:AA:AA:CC")
ALL_MACs_MANITOR.append("AA:AA:AA:AA:AA:DD")
ALL_MACs_MANITOR.append("c4:65:16:c0:28:05")

